name: CI-CD
on:
  push:
    branches: [ main ]
jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: install dependencies
        run: npm install && npm ci

      - name: check format
        run: npm run format
    
  build:
    needs: format_check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: login to Docker Hub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" docker.io
      
      - name: build docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app-devops --output type=tar,dest=out.tar . 
          pwd
          ls 
      
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /out
      
      
  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /out

      - name: load and push docker image
        run: |
          docker load --input /out
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app-devops:latest 
      